language: python
python:
  - "3.5"
# command to install depenencies
install:
  - pip install -r requirements.txt

# command to run unit tests
script: python twotebotapi/manage.py test twotebotapi/twotebotapp/bot_utils/
