# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=255)),
                ('needs_approval', models.BooleanField()),
                ('approved', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
