# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
