# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_APP', '0002_auto_20170227_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
