# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_APP', '0003_tweets_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='scheduled',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='default_send_interval',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tweets',
            name='time_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
