# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_APP', '0004_auto_20170227_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='approved',
            field=models.IntegerField(choices=[(0, 'needs_action'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
