# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 21:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twotebotapp', '0002_tweets_task_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('favorite_count', models.IntegerField(default=-1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_str', models.CharField(db_index=True, default='', max_length=256)),
                ('screen_name', models.CharField(blank=True, max_length=256, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=256, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('protected', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('lang', models.CharField(blank=True, max_length=256, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('statuses_count', models.IntegerField(blank=True, null=True)),
                ('friends_count', models.IntegerField(blank=True, null=True)),
                ('favourites_count', models.IntegerField(default=-1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ignore_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[841013993602863104], size=None),
        ),
        migrations.AddField(
            model_name='streamedtweet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twotebotapp.User'),
        ),
    ]
