# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twotebotapp', '0003_auto_20170322_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ignore_users',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
