# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 21:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twotebotapp', '0003_auto_20170329_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='ignore_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None),
        ),
    ]
